version: '3'
services:
#mssql docker
  kino-sql:
    image: mcr.microsoft.com/mssql/server:2017-latest-ubuntu
    restart: unless-stopped
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=QWElkj132!
      - MSSQL_PID=Developer
    ports:
      - 1401:1433
    networks:
      - kinonet

  kino-api:
    restart: unless-stopped
    build:
      context: .
    environment:
      - ConnectionStrings:Kino=Server=kino-sql,1433;Database=Kino;User=sa;Password=QWElkj132!;ConnectRetryCount=0
    ports:
      - 32958:80
    networks:
      - kinonet
    links:
      - kino-sql
    depends_on:
      - kino-sql
      
networks:
  kinonet:
    driver: bridge